version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - sources
        - abcjs-widget
        - abcjs-headless

sphinx:
  configuration: docs/conf.py
