name: pyabc2
channels:
  - conda-forge
  - emscripten-forge-4x
  - nodefaults
dependencies:
  - xeus-python
  - pip
  #
  # sources
  - numpy ==2.*
  - pandas ==2.*
  - requests ==2.*
  #
  # abcjs widget
  - anywidget
  - ipywidgets
  - traitlets
  #
  - pip:
    - pyabc2 ==0.1.3
